spring:
  application:
    name: origin
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: ${chunk.job.name:helloWorldJob} # 여기 기본값이 helloWorldJob이어야 함
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?reWriteBatchedInserts=true
    driver-class-name: org.postgresql.Driver
    username: root
    password: password
logging:
  level:
    org.springframework.batch.item.database: DEBUG